name: Linux CI

on:
  push:
    branches:
      - M1K-Version-1.3-release
  workflow_dispatch:
 # pull_request:
 #   branches:
 #     - M1K-Version-1.3-release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04,ubuntu-24.04-arm] #[ubuntu-20.04, macos-latest, windows-latest]
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' 

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y dos2unix cmake || true
        sudo apt-get install -y libudev-dev libusb-1.0-0-dev libboost-all-dev || true

        pip install numpy build setuptools pyinstaller tk
        
    - name: Clone and build libsmu (Linux)
      if: runner.os == 'Linux'
      run: |
        git clone https://github.com/sounddrill31/libsmu.git
        cd libsmu
        mkdir build && cd build
        cmake -DCMAKE_INSTALL_PREFIX=/usr/ ..
        make
        sudo make install
        cd ../..

    - name: Use PyInstaller to package Alice (Linux)
      run: |
        cp launcher/alice.py alice.py || true
        pyinstaller alice.spec # Might output to dist/alice
        
        tree dist

    - name: Create Package with Dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
          export ARCH="$(uname -m)"
          export VERSION="$(echo "$GITHUB_SHA" | cut -c 1-9)"
          export APP=Alice

          # Prepare AppDir structure
          mkdir -p AppDir/shared/lib
          mkdir -p AppDir/usr/share/applications
          mkdir -p AppDir/usr/share/Alice-M1K/
          ln -s ./usr/share ./AppDir/share

          # Copy libsmu library
          cp /usr/lib/$ARCH-linux-gnu/libsmu.so.1.0.4  AppDir/shared/lib
          ln -s ./libsmu.so.1.0.4 AppDir/shared/lib/libsmu.so.1
          ln -s ./libsmu.so.1.0.4 AppDir/shared/lib/libsmu.so

          # Copy runner script
          cp launcher/AppRun AppDir/AppRun
          chmod +x AppDir/AppRun
          dos2unix AppDir/AppRun # just in case

          # Copy key system libraries that might not be auto-detected
          # Note: Be selective and only include necessary libraries
          cp /usr/lib/$ARCH-linux-gnu/libudev.so.1     AppDir/shared/lib/
          cp /usr/lib/$ARCH-linux-gnu/libusb-1.0.so.0  AppDir/shared/lib/

          mv dist/alice/* AppDir/usr/share/Alice-M1K/

          ( export ARCH="$(uname -m)" # Just to be double sure
            cd AppDir
            wget "https://raw.githubusercontent.com/VHSgunzo/sharun/refs/heads/main/lib4bin" -O ./lib4bin
            chmod +x ./lib4bin
            xvfb-run -a -- ./lib4bin -p -v -e -k -w \
              usr/share/Alice-M1K/alice

            # ln ./sharun ./AppRun 
            ./sharun -g
          )

          wget "https://github.com/VHSgunzo/uruntime/releases/latest/download/uruntime-appimage-dwarfs-$ARCH" -O uruntime
          chmod +x ./uruntime
          ./uruntime --appimage-mkdwarfs -f \
          	--set-owner 0 --set-group 0 \
          	--no-history --no-create-timestamp \
          	--compression zstd:level=22 -S26 -B32 \
          	--header uruntime \
          	-i ./AppDir -o "$APP"-"$VERSION"-anylinux-"$ARCH".AppImage

          # List the generated AppImage
          ls -l Alice*.AppImage
          chmod +x Alice*.AppImage

    - name: Test AppImage
      if: runner.os == 'linux'
      continue-on-error: true
      run: |
          timeout -k 10s 120s stdbuf -oL ./Alice*.AppImage || echo "Tried to run Alice"

    - name: Upload Release Asset (Linux/Wrappe)
      if: runner.os == 'linux'
      uses: softprops/action-gh-release@v1
      with:
        target_commitish: ${{ github.ref_name }}
        files: Alice*.AppImage
        name: Alice for M1K
        tag_name: ${{ github.run_id }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
